{
 "title": "Block Parser",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Number of parsed blocks",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time(merchantapi_blockparser_blockparsed_counter[$__rate_interval])",
     "legendFormat": "parsed blocks"
    }
   ]
  },
  {
   "title": "Best block height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "merchantapi_blockparser_bestblockheight",
     "legendFormat": "block height"
    }
   ]
  },
  {
   "title": "Unparsed blocks (in queue for parsing)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "merchantapi_blockparser_blockparsingqueue"
    }
   ]
  },
  {
   "title": "Average time spent parsing blocks",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(merchantapi_blockparser_blockparsing_duration_seconds_sum[1m]) / rate(merchantapi_blockparser_blockparsing_duration_seconds_count[1m])",
     "legendFormat": "time spent parsing blocks"
    }
   ]
  },
  {
   "title": "Total seconds spent parsing blocks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(merchantapi_blockparser_blockparsing_duration_seconds_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}