{
 "title": "Callbacks",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Processing notifications with error",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "merchantapi_notificationshandler_notification_with_error",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All callbacks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time(merchantapi_notificationshandler_successful_callbacks_counter[$__rate_interval])",
     "legendFormat": "successful callbacks"
    },
    {
     "expr": "max_over_time(merchantapi_notificationshandler_failed_callbacks_counter[$__rate_interval])",
     "legendFormat": "failed callbacks"
    }
   ]
  },
  {
   "title": "Queued notifications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "merchantapi_notificationshandler_notification_in_queue",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average duration of callbacks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(merchantapi_notificationshandler_callback_duration_seconds_sum [1m])/rate(merchantapi_notificationshandler_callback_duration_seconds_count [1m])",
     "legendFormat": "duration of callbacks"
    }
   ]
  }
 ]
}