{
 "title": "Mempool checker",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Resubmits interrupted with exceptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(merchantapi_mempoolchecker_exceptions_resubmit_counter[$__rate_interval])",
     "legendFormat": "Number of exceptions"
    }
   ]
  },
  {
   "title": "Average txs in mempool last minute",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(merchantapi_mempoolchecker_tx_in_mempool[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All resubmits",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time(merchantapi_mempoolchecker_successful_resubmit_counter[$__rate_interval])",
     "legendFormat": "number of all successful resubmits"
    },
    {
     "expr": "max_over_time(merchantapi_mempoolchecker_unsuccessful_resubmit_counter[$__rate_interval])",
     "legendFormat": "number of all unsuccessful/interrupted resubmits"
    }
   ]
  },
  {
   "title": "All transactions with MempoolCheckerMissingInputsRetries",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(merchantapi_mempoolchecker_tx_missing_inputs_max_counter[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All transactions resubmitted",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(merchantapi_mempoolchecker_tx_response_success_counter[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time spent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(merchantapi_mempoolchecker_getrawmempool_duration_seconds_sum [1m]) / rate(merchantapi_mempoolchecker_getrawmempool_duration_seconds_count [1m])",
     "legendFormat": "getrawmempool response from node"
    },
    {
     "expr": "rate(merchantapi_getmissingtransactions_duration_seconds_sum [1m]) / rate(merchantapi_getmissingtransactions_duration_seconds_count [1m])",
     "legendFormat": "database execution time for the query which transactions must be resubmitted"
    }
   ]
  },
  {
   "title": "All transaction resubmitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "max_over_time(merchantapi_mempoolchecker_tx_response_success_counter[$__rate_interval])",
     "legendFormat": "Number of  transactions with success response"
    },
    {
     "expr": "max_over_time(merchantapi_mempoolchecker_tx_response_failure_counter[$__rate_interval])",
     "legendFormat": "Number of transactions with failure response"
    },
    {
     "expr": "max_over_time(merchantapi_mempoolchecker_tx_missing_counter[$__rate_interval])-max_over_time(merchantapi_mempoolchecker_tx_response_success_counter[$__rate_interval])-max_over_time(merchantapi_mempoolchecker_tx_response_failure_counter[$__rate_interval])",
     "legendFormat": "All ignored failures"
    },
    {
     "expr": "max_over_time(merchantapi_mempoolchecker_tx_missing_counter[$__rate_interval])",
     "legendFormat": "All missing transactions"
    }
   ]
  }
 ]
}