{
 "title": "Mempool Checker",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Transactions successfully resubmitted",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(merchantapi_mempoolchecker_tx_response_success_counter[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average resubmit rounds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "increase(merchantapi_mempoolchecker_successful_resubmit_counter[$__rate_interval])",
     "legendFormat": "successful resubmit rounds"
    },
    {
     "expr": "increase(merchantapi_mempoolchecker_unsuccessful_resubmit_counter[$__rate_interval])",
     "legendFormat": "unsuccessful/interrupted resubmit rounds"
    },
    {
     "expr": "increase(merchantapi_mempoolchecker_exceptions_resubmit_counter[$__rate_interval])",
     "legendFormat": "Interrupted with exception"
    }
   ]
  },
  {
   "title": "Min txs in mempool",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "merchantapi_mempoolchecker_min_tx_in_mempool",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max txs in mempool",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "merchantapi_mempoolchecker_min_tx_in_mempool",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time spent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "rate(merchantapi_mempoolchecker_getrawmempool_duration_seconds_sum [1m]) / rate(merchantapi_mempoolchecker_getrawmempool_duration_seconds_count [1m])",
     "legendFormat": "getrawmempool response from node"
    },
    {
     "expr": "rate(merchantapi_mempoolchecker_getmissingtransactions_duration_seconds_sum [1m]) / rate(merchantapi_mempoolchecker_getmissingtransactions_duration_seconds_count [1m])",
     "legendFormat": "database execution time for the query which transactions must be resubmitted"
    }
   ]
  },
  {
   "title": "All txs with MempoolCheckerMissingInputsRetries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(merchantapi_mempoolchecker_tx_missing_inputs_max_counter[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All transactions resubmitted",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max_over_time(merchantapi_mempoolchecker_tx_response_success_counter[$__rate_interval])",
     "legendFormat": "Number of  transactions with success response"
    },
    {
     "expr": "max_over_time(merchantapi_mempoolchecker_tx_response_failure_counter[$__rate_interval])",
     "legendFormat": "Number of transactions with failure response"
    },
    {
     "expr": "max_over_time(merchantapi_mempoolchecker_tx_missing_counter[$__rate_interval])-max_over_time(merchantapi_mempoolchecker_tx_response_success_counter[$__rate_interval])-max_over_time(merchantapi_mempoolchecker_tx_response_failure_counter[$__rate_interval])",
     "legendFormat": "All ignored failures"
    },
    {
     "expr": "max_over_time(merchantapi_mempoolchecker_tx_missing_counter[$__rate_interval])",
     "legendFormat": "All missing transactions"
    }
   ]
  }
 ]
}