{
 "title": "Transaction Submissions",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "mAPI status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Average txs/request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max_over_time(merchantapi_mapi_tx_anonymous_user_counter[$__rate_interval]) + \r\nmax_over_time(merchantapi_mapi_tx_authenticated_user_counter[$__rate_interval]))/ max_over_time(merchantapi_mapi_request_counter[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All transactions counter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(merchantapi_mapi_tx_anonymous_user_counter[$__rate_interval]))+\r\nmax(max_over_time(merchantapi_mapi_tx_authenticated_user_counter[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "merchantapi_mapi_any_bitcoind_responding",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average number of errors returned to customer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{code=~\"5.*\",action=\"SubmitError\"}[$__rate_interval]))",
     "legendFormat": "number of errors 500"
    },
    {
     "expr": "sum(increase(http_requests_received_total{code=~\"4.*\",action=\"SubmitError\"}[$__rate_interval]))",
     "legendFormat": "number of errors 400"
    }
   ]
  },
  {
   "title": "Error 500/all responses",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(http_requests_received_total{code=~\"5.*\", action=\"SubmitError\"}[$__rate_interval])) / sum(max_over_time(http_requests_received_total{controller=\"Mapi\", method=\"POST\"}[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of requests submitted by client",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time(http_requests_received_total{controller=\"Mapi\",action=\"SubmitTx\"}[$__rate_interval])",
     "legendFormat": "submitTx (single)"
    },
    {
     "expr": "max_over_time(http_requests_received_total{controller=\"Mapi\",action=\"SubmitTxs\"}[$__rate_interval])",
     "legendFormat": "submitTxs (batch)"
    },
    { "expression": "$A + $B", "legendFormat": "Sum", "type": "math" }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(merchantapi_mapi_request_counter[$__rate_interval])",
     "legendFormat": "requests per second"
    }
   ]
  },
  {
   "title": "Total number of transactions submitted by client",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time(merchantapi_mapi_tx_authenticated_user_counter[$__rate_interval])",
     "legendFormat": "transactions submitted by authenticated users"
    },
    {
     "expr": "max_over_time(merchantapi_mapi_tx_anonymous_user_counter[$__rate_interval])",
     "legendFormat": "transactions submitted by anonymous users"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Transaction throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(merchantapi_mapi_tx_anonymous_user_counter[$__rate_interval]) + rate(merchantapi_mapi_tx_authenticated_user_counter[$__rate_interval])",
     "legendFormat": "processed transactions per second"
    }
   ]
  },
  {
   "title": "Average response time for client requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{controller=\"Mapi\",action=\"SubmitTx\"} [1m])/rate(http_request_duration_seconds_count{controller=\"Mapi\",action=\"SubmitTx\"} [1m])",
     "legendFormat": "submitTx"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{controller=\"Mapi\",action=\"SubmitTxs\"} [1m])/rate(http_request_duration_seconds_count{controller=\"Mapi\",action=\"SubmitTxs\"} [1m])",
     "legendFormat": "submitTxs"
    }
   ]
  },
  {
   "title": "Ratio of transaction responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(merchantapi_mapi_tx_response_success_counter[$__rate_interval])/ (rate(merchantapi_mapi_tx_anonymous_user_counter[$__rate_interval]) + \r\nrate(merchantapi_mapi_tx_authenticated_user_counter[$__rate_interval]))",
     "legendFormat": "success responses"
    },
    {
     "expr": "rate(merchantapi_mapi_tx_response_failure_counter[$__rate_interval]) / (rate(merchantapi_mapi_tx_anonymous_user_counter[$__rate_interval]) + \r\nrate(merchantapi_mapi_tx_authenticated_user_counter[$__rate_interval]))",
     "legendFormat": "failure responses"
    },
    {
     "expr": "rate(merchantapi_mapi_tx_response_failure_retryable_counter[$__rate_interval]) / (rate(merchantapi_mapi_tx_anonymous_user_counter[$__rate_interval]) + \r\nrate(merchantapi_mapi_tx_authenticated_user_counter[$__rate_interval]))",
     "legendFormat": "failure retryable responses"
    },
    {
     "expr": "(rate(merchantapi_mapi_tx_anonymous_user_counter[$__rate_interval]) + \r\nrate(merchantapi_mapi_tx_authenticated_user_counter[$__rate_interval]) - rate(merchantapi_mapi_tx_response_failure_counter[$__rate_interval])- rate(merchantapi_mapi_tx_response_success_counter[$__rate_interval])) / (rate(merchantapi_mapi_tx_anonymous_user_counter[$__rate_interval]) + \r\nrate(merchantapi_mapi_tx_authenticated_user_counter[$__rate_interval]))",
     "legendFormat": "exception"
    }
   ]
  },
  {
   "title": "Total number of transactions sent to node and node responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time(merchantapi_mapi_tx_sent_to_node_counter[$__rate_interval])",
     "legendFormat": "transactions sent to node"
    },
    {
     "expr": "max_over_time(merchantapi_mapi_tx_accepted_by_node_counter[$__rate_interval])",
     "legendFormat": "transactions accepted by node"
    },
    {
     "expr": "max_over_time(merchantapi_mapi_tx_rejected_by_node_counter[$__rate_interval])",
     "legendFormat": "transactions rejected by node"
    },
    {
     "expr": "max_over_time(merchantapi_mapi_tx_submit_exception_counter[$__rate_interval])",
     "legendFormat": "transactions with submit exception"
    }
   ]
  },
  {
   "title": "Average time spent waiting for response from node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(merchantapi_rpcmulticlient_gettxouts_duration_seconds_sum [1m]) / rate(merchantapi_rpcmulticlient_gettxouts_duration_seconds_count [1m])",
     "legendFormat": "gettxouts response"
    },
    {
     "expr": "rate(merchantapi_rpcmulticlient_sendrawtxs_duration_seconds_sum [1m]) / rate(merchantapi_rpcmulticlient_sendrawtxs_duration_seconds_count [1m])",
     "legendFormat": "sendrawtransactions response"
    }
   ]
  },
  {
   "title": "Missing inputs status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "merchantapi_mapi_tx_missing_inputs_counter",
     "legendFormat": "Missing inputs"
    },
    {
     "expr": "merchantapi_mapi_tx_resent_missing_inputs_counter",
     "legendFormat": "Parent was resent"
    },
    {
     "expr": "merchantapi_mapi_tx_was_mined_missing_inputs_counter",
     "legendFormat": "Already in block"
    },
    {
     "expr": "merchantapi_mapi_tx_invalid_block_missing_inputs_counter",
     "legendFormat": "Invalid block"
    }
   ]
  }
 ]
}