{
 "title": "Transaction submission",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total response time for client requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Time [s]" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{controller=\"Mapi\",action=\"SubmitTx\"} [1m])",
     "legendFormat": "SubmitTx"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{controller=\"Mapi\",action=\"SubmitTxs\"} [1m])",
     "legendFormat": "SubmitTxs"
    }
   ]
  },
  {
   "title": "Total number of requests submitted by client",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_received_total{controller=\"Mapi\",action=\"SubmitTx\"}[1m])",
     "legendFormat": "SubmitTx"
    },
    {
     "expr": "rate(http_requests_received_total{controller=\"Mapi\",action=\"SubmitTxs\"}[1m])",
     "legendFormat": "SubmitTxs"
    }
   ]
  },
  {
   "title": "Total number of transactions submitted by client",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(merchantapi_mapi_tx_authenticated_user_counter[1m])",
     "legendFormat": "transactions submitted by authenticated users"
    },
    {
     "expr": "rate(merchantapi_mapi_tx_anonymous_user_counter[1m])",
     "legendFormat": "transactions submitted by anonymous users"
    }
   ]
  },
  {
   "title": "Total number of mAPI responses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(merchantapi_mapi_tx_response_success_counter[1m])",
     "legendFormat": "success responses"
    },
    {
     "expr": "rate(merchantapi_mapi_tx_response_failure_counter[1m])",
     "legendFormat": "failure responses"
    }
   ]
  },
  {
   "title": "Total number of transactions sent to node and node responses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(merchantapi_mapi_tx_sent_to_node_counter[1m])",
     "legendFormat": "transactions sent to node"
    },
    {
     "expr": "rate(merchantapi_mapi_tx_accepted_by_node_counter[1m])",
     "legendFormat": "transactions accepted by node"
    },
    {
     "expr": "rate(merchantapi_mapi_tx_rejected_by_node_counter[1m])",
     "legendFormat": "transactions rejected by node"
    },
    {
     "expr": "rate(merchantapi_mapi_tx_submit_exception_counter[1m])",
     "legendFormat": "transactions with submit exception"
    }
   ]
  },
  {
   "title": "Total time spend waiting for response from node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Time [s]" }
   ],
   "targets": [
    {
     "expr": "rate(merchantapi_rpcmulticlient_gettxouts_duration_seconds_sum [1m])",
     "legendFormat": "gettxouts response"
    },
    {
     "expr": "rate(merchantapi_rpcmulticlient_sendrawtxs_duration_seconds_sum [1m])",
     "legendFormat": "sendrawtransactions response"
    }
   ]
  },
  {
   "title": "mAPI status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Total number of 500 errors returned to customer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_received_total{code=\".*5\"} [1m])",
     "legendFormat": "number of errors returned to customer"
    }
   ]
  }
 ]
}